# Generated by Django 4.2.2 on 2023-06-14 18:52

import apps.entity.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=9)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(default='/default_logo.png', upload_to=apps.entity.models.Entity.logo_upload_rename)),
                ('business_name', models.CharField(blank=True, max_length=100)),
                ('nif', models.CharField(blank=True, max_length=9)),
                ('registry_number', models.CharField(blank=True, max_length=100)),
                ('social_address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(default='España', max_length=100)),
                ('is_same_address', models.BooleanField(default=True)),
                ('fiscal_address', models.CharField(blank=True, max_length=100)),
                ('fiscal_postal_code', models.CharField(blank=True, max_length=5)),
                ('fiscal_city', models.CharField(blank=True, max_length=100)),
                ('fiscal_province', models.CharField(blank=True, max_length=100)),
                ('fiscal_country', models.CharField(blank=True, max_length=100)),
                ('join_password', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyCensusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jcf_number', models.IntegerField(blank=True, null=True)),
                ('census_number', models.IntegerField(blank=True, null=True)),
                ('commission', models.CharField(max_length=100)),
                ('surnames', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=5)),
                ('phone', models.CharField(blank=True, max_length=9)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('document_id', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('reward', models.CharField(max_length=100)),
                ('affiliate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliate.affiliate')),
            ],
        ),
        migrations.CreateModel(
            name='YearlyCensus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('entries', models.ManyToManyField(to='entity.yearlycensusentry')),
            ],
        ),
        migrations.CreateModel(
            name='DirectoratePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='entity.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.directorateposition')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='affiliate.affiliate')),
            ],
        ),
    ]
