# Generated by Django 4.2.2 on 2023-06-14 18:52

import apps.affiliate.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('census_number', models.IntegerField(blank=True, null=True)),
                ('jcf_number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('surnames', models.CharField(max_length=100)),
                ('document_type', models.IntegerField(choices=[(1, 'DNI'), (2, 'NIE'), (3, 'Pasaporte')], default=1)),
                ('document_id', models.CharField(max_length=9)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=9)),
                ('photo', models.ImageField(default='/default_photo.png', upload_to=apps.affiliate.models.Affiliate.photo_upload_rename)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], default='M', max_length=9)),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(default='España', max_length=100)),
                ('has_legal_tutor', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('census_number', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PaymentChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.IntegerField(choices=[(1, 'Efectivo'), (2, 'Domiciliación bancaria'), (3, 'Transferencia bancaria')], default=1)),
                ('account_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('account_iban', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_choice', to='affiliate.affiliate')),
            ],
        ),
    ]
