# Generated by Django 4.2.2 on 2023-06-14 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliate', '0001_initial'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity'),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='legal_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tutor', to='affiliate.affiliate'),
        ),
    ]
